### ISSUE TITLE
Invalid JSON Attribut

### ISSUE THREAD

**Issue by Paxi180** [mongodb/go-client-mongodb-ops-manager#151]
Hi,

I've got the error "INVALID_JSON_ATTRIBUT" on my API PUT call can someone support me?

`t := digest.NewTransport("<public-key>", "private-key")
	tc, err := t.Client()
	if err != nil {
		log.Fatalf(err.Error())
	}
	clientops := opsmngr.SetBaseURL("<OpsManager_URL>")
	client, err := opsmngr.New(tc, clientops)
	if err != nil {
		log.Fatalf(err.Error())
	} else {
		fmt.Println("running")
	}

	var projectId string
	fmt.Println("Please enter the projectID")
	fmt.Scanln(&projectId)

	a, _, err := client.Automation.GetConfig(context.Background(), projectId)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", a)

	roles := make([]*opsmngr.Role, 2)

	var r1 opsmngr.Role
	r1.Role = "clusterMonitor"
	r1.Database = "admin"

	var r2 opsmngr.Role
	r2.Role = "readAnyDatabase"
	r2.Database = "admin"

	roles = append(roles, &r1, &r2)

	var u opsmngr.MongoDBUser
	u.Database = "admin"
	u.Password = RandStringRunes(20)
	u.Roles = roles
	u.Username = "mongomirror"

	a.Auth.UsersWanted = append(a.Auth.UsersWanted, &u)

	fmt.Printf("%+v\n", a)

	_, err = client.Automation.UpdateConfig(context.Background(), projectId, a)
	if err != nil {
		log.Fatal(err)
	}`

Thanks,
Pascal

**Comment by Paxi180** [comment]
Hi @tibulca,
thanks for your help.

Unfortunately I get now an unexpected error where I don't know how I can fix it.

`	a, _, err := client.Automation.GetConfig(context.Background(), projectId)
	if err != nil {
		log.Fatal(err)
	}

	u := opsmngr.MongoDBUser{
		Username: "mongomirror",
		Password: RandStringRunes(20),
		Database: "admin",
		Roles: []*opsmngr.Role{
			{Role: "clusterMonitor", Database: "admin"},
			{Role: "readAnyDatabase", Database: "admin"},
		},
	}

	a.Auth.UsersWanted = append(a.Auth.UsersWanted, &u)

	fmt.Printf("%+v\n", a)

	_, err = client.Automation.UpdateConfig(context.Background(), projectId, a)
	if err != nil {
		log.Fatal(err)
	}`

Thanks,
Pascal

**Comment by Paxi180** [comment]
And another question:
DO you prefer to use this package or to use the mongocli with golang?

**Comment by tibulca** [comment]
@Paxi180 
Is `client.Automation.GetConfig` returning the unexpected error? (I assume this was working previously since you were getting the INVALID_JSON_ATTRIBUTE when updating the automation config, so after this line).

can you provide this information:
1. full source code (the new one) and the line where you get the unexpected error
2. the error message as it is logged in the terminal
3. OpsManager version

> DO you prefer to use this package or to use the mongocli with golang?
Here it depends on the use case. If you're building your own golang application that interacts with OpsManager, then you should use this package. If you only want to manage OpsManager or automate some of its configuration, then I recommend using mongocli (which you can use directly or from some simple scripts) https://www.mongodb.com/docs/mongocli/master/command/mongocli-ops-manager-dbusers-create/

**Comment by Paxi180** [comment]
@tibulca 
My goal in the future is to develop a programm that executes automatically a mongomirror if a customer click on a button.
We want to include this also in our own API in the future.


Full code:
`package main

import (
	"context"
	"fmt"
	"github.com/mongodb-forks/digest"
	"go.mongodb.org/ops-manager/opsmngr"
	"log"
	"math/rand"
	"time"
)

func init() {
	rand.Seed(time.Now().UnixNano())
}

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")

func RandStringRunes(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}

func main() {
	t := digest.NewTransport("<public-key>", "<private-key>")
	tc, err := t.Client()
	if err != nil {
		log.Fatalf(err.Error())
	}

	// Note: If no Base URL is set the client is set to work with Cloud Manager by default
	clientops := opsmngr.SetBaseURL("<OpsManager_URL>")
	client, err := opsmngr.New(tc, clientops)
	if err != nil {
		log.Fatalf(err.Error())
	} else {
		fmt.Println("running")
	}

	var projectId string
	fmt.Println("Please enter the projectID")
	fmt.Scanln(&projectId)

	a, _, err := client.Automation.GetConfig(context.Background(), projectId)
	if err != nil {
		log.Fatal(err)
	}

	u := opsmngr.MongoDBUser{
		Username: "mongomirror",
		Password: RandStringRunes(20),
		Database: "admin",
		Roles: []*opsmngr.Role{
			{Role: "clusterMonitor", Database: "admin"},
			{Role: "readAnyDatabase", Database: "admin"},
		},
	}

	a.Auth.UsersWanted = append(a.Auth.UsersWanted, &u)

	fmt.Printf("%+v\n", a)

	_, err = client.Automation.UpdateConfig(context.Background(), projectId, a)
	if err != nil {
		log.Fatal(err)
	}
}
`

Error message:
`2022/05/17 10:51:55 PUT https://<OpsManager_URL>/api/public/v1.0/groups/<projectID>/automationConfig: 500 (request "UNEXPECTED_ERROR") Unexpected error.

Process finished with the exit code 1`

Thanks,
Pascal

**Comment by tibulca** [comment]
> Error message:
`2022/05/17 10:51:55 PUT https://<OpsManager_URL>/api/public/v1.0/groups//automationConfig: 500 (request "UNEXPECTED_ERROR") Unexpected error.

I assume the url was edited and the projectId removed (`groups//automationConfig` was actually `groups/<project_id>/automationConfig`)

The code looks ok now and I was able to update the automation config on my local env (and verified in the OpsManager UI that the user was created too). 
For more debugging and finding the cause of the "UNEXPECTED_ERROR", we'll need the OpsManager logs.
Please open a support ticket for this.

Thanks,
Ciprian

**Comment by Paxi180** [comment]
okay, i opened a support ticket.

Thanks for your support, have a nice day! :)
