### ISSUE TITLE
Unable to connect Ops Manager using Public API

### ISSUE THREAD

**Issue by gauravtaneja1984** [mongodb/go-client-mongodb-ops-manager#29]
Hi Team,

I am unable to access ops manager using public API.I am getting below error.

 curl --user '{XXX}:{XXX}' --digest --header 'Accept: application/json' --include  --request GET "<xxx>:<xx>/api/public/v1.0/groups?pretty=true"

Content-Type: application/json
Content-Length: 106

{
  "reason" : "Unauthorized",
  "error" : 401,
  "detail" : "You are not authorized for this resource."
}

Thanks!!

**Comment by gssbzn** [comment]
Hi @gauravtaneja1984 seems like you're trying to use `curl` to access the API. This project is a library for golang and as such we reserve to address issues related with the library. If you have a problem with the library please let us know what version are you using, a sample of the code or a sample project with the issue and any error you're getting in the code along with the expected result.

For any issue related to Ops Manager please contact [MongoDB support](https://support.mongodb.com/welcome) directly.
