### ISSUE TITLE
Getting 500 error attempting to update the automation config

### ISSUE THREAD

**Issue by MMartyn** [mongodb/go-client-mongodb-ops-manager#60]
**Describe the bug**
I have created a project/group and am now trying to update the automation config to create the processes/replicaset and I am getting an error. I have even tried to use the jsonBlob (https://github.com/mongodb/go-client-mongodb-ops-manager/blob/master/opsmngr/automation_config_test.go#L26) from your test case and that also reports a 500. Weirdly, I can also get it into a state where it tells me that members in my replicaset "must have priority 0 when not eligible to become primary" so maybe that is a clue to what is going on.

Basic reproduction:
Create a project
Unmarshal the jsonBlob into an AutomationConfig object
Attempt to apply the AutomationConfig to the project

Note: I did confirm that I am passing the correct project id.

**Expected behavior**
I would expect either a validation error if something was wrong, or for it to work.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by gssbzn** [comment]
Hi @MMartyn, can you please indicate if this is Ops Manager or Cloud Manager and in case it's Ops Manager what version?

Have you reviewed [our documentation](https://docs.opsmanager.mongodb.com/current/reference/api/automation-config/) on how the automation config works, in general we don't recommend directly updating it, you should do a GET first of the current state, and then modify that state with the desired goal state and apply that as a PUT, our tests are for us to test serialization/deserialization and not intended to represent a full working automation config

If after GETing and PUTing the config you still get a 500 error, can you please provide the Automation config you're trying to apply? and in case of this being Ops Manager any logs?

Also given this is a 500 error I would recommend you to open a support case via, https://support.mongodb.com/ where you can probably share all the information I'm asking in a more secure way than a public forum

**Comment by MMartyn** [comment]
Thanks for the response @gssbzn. 

I am using cloud manager and have reviewed the docs. I am actually converting our current direct api calls to using this library. 

I'll try doing the GET first and let you know if that solves the issue, if not I'll open the support ticket as suggested. Thanks.

**Comment by gssbzn** [comment]
FWIW here's an example of a config we know works, it should deploy a 3 member replicaset

```json
{
  "auth": {
    "authoritativeSet": false,
    "autoAuthMechanism": "SCRAM-SHA-256",
    "autoAuthMechanisms": [
      "SCRAM-SHA-256"
    ],
    "autoAuthRestrictions": [],
    "autoPwd": "<redacted>>",
    "autoUser": "mms-automation",
    "deploymentAuthMechanisms": [
      "SCRAM-SHA-256"
    ],
    "disabled": false,
    "key": "<redacted>",
    "keyfile": "/var/lib/mongodb-mms-automation/keyfile",
    "keyfileWindows": "%SystemDrive%\\MMSAutomation\\versions\\keyfile",
    "usersDeleted": [],
    "usersWanted": []
  },
  "backupVersions": [],
  "balancer": {},
  "cpsModules": [],
  "indexConfigs": [],
  "kerberos": {
    "serviceName": "mongodb"
  },
  "ldap": {},
  "mongoDbVersions": [<removed for simplicity>],
  "monitoringVersions": [
    {
      "name": "7.2.0.488-1",
      "hostname": "<redacted>"
    }
  ],
  "options": {
    "downloadBase": "/var/lib/mongodb-mms-automation",
    "downloadBaseWindows": "%SystemDrive%\\MMSAutomation\\versions"
  },
  "processes": [
    {
      "args2_6": {
        "net": {
          "port": 27000
        },
        "replication": {
          "replSetName": "e2e-cluster-732"
        },
        "storage": {
          "dbPath": "/data/e2e-cluster-732/27000"
        },
        "systemLog": {
          "destination": "file",
          "path": "/data/e2e-cluster-732/27000/mongodb.log"
        }
      },
      "authSchemaVersion": 5,
      "disabled": false,
      "featureCompatibilityVersion": "4.2",
      "hostname": "<redacted>",
      "logRotate": {
        "sizeThresholdMB": 1000,
        "timeThresholdHrs": 24
      },
      "manualMode": false,
      "name": "e2e-cluster-732_0",
      "numCores": 0,
      "processType": "mongod",
      "version": "4.2.0"
    },
    {
      "args2_6": {
        "net": {
          "port": 27001
        },
        "replication": {
          "replSetName": "e2e-cluster-732"
        },
        "storage": {
          "dbPath": "/data/e2e-cluster-732/27001"
        },
        "systemLog": {
          "destination": "file",
          "path": "/data/e2e-cluster-732/27001/mongodb.log"
        }
      },
      "authSchemaVersion": 5,
      "disabled": false,
      "featureCompatibilityVersion": "4.2",
      "hostname": "<redacted>",
      "logRotate": {
        "sizeThresholdMB": 1000,
        "timeThresholdHrs": 24
      },
      "manualMode": false,
      "name": "e2e-cluster-732_1",
      "numCores": 0,
      "processType": "mongod",
      "version": "4.2.0"
    },
    {
      "args2_6": {
        "net": {
          "port": 27002
        },
        "replication": {
          "replSetName": "e2e-cluster-732"
        },
        "storage": {
          "dbPath": "/data/e2e-cluster-732/27002"
        },
        "systemLog": {
          "destination": "file",
          "path": "/data/e2e-cluster-732/27002/mongodb.log"
        }
      },
      "authSchemaVersion": 5,
      "disabled": false,
      "featureCompatibilityVersion": "4.2",
      "hostname": "ip-10-122-4-66.ec2.internal",
      "logRotate": {
        "sizeThresholdMB": 1000,
        "timeThresholdHrs": 24
      },
      "manualMode": false,
      "name": "e2e-cluster-732_2",
      "numCores": 0,
      "processType": "mongod",
      "version": "4.2.0"
    }
  ],
  "replicaSets": [
    {
      "_id": "e2e-cluster-732",
      "protocolVersion": "1",
      "members": [
        {
          "_id": 0,
          "arbiterOnly": false,
          "buildIndexes": true,
          "hidden": false,
          "host": "e2e-cluster-732_0",
          "priority": 1,
          "slaveDelay": 0,
          "tags": null,
          "votes": 1
        },
        {
          "_id": 1,
          "arbiterOnly": false,
          "buildIndexes": true,
          "hidden": false,
          "host": "e2e-cluster-732_1",
          "priority": 1,
          "slaveDelay": 0,
          "tags": null,
          "votes": 1
        },
        {
          "_id": 2,
          "arbiterOnly": false,
          "buildIndexes": true,
          "hidden": false,
          "host": "e2e-cluster-732_2",
          "priority": 1,
          "slaveDelay": 0,
          "tags": null,
          "votes": 1
        }
      ]
    }
  ],
  "roles": [],
  "sharding": [],
  "tls": {
    "clientCertificateMode": "OPTIONAL"
  },
  "uiBaseUrl": null,
  "version": 2080
}

```

**Comment by MMartyn** [comment]
Thanks @gssbzn, the GET first worked. I believe it was because I wasn't passing more than the mongodb version name in the mongoDbVersions where as the GET had that completely filled out. 

Side note: It also wouldn't work until I explicitly set buildIndexes on the members of the replicaset
